[workspace]
name = "val3dity"
version = "2.7.0b0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
cgal-cpp = ">=6"
libboost-devel = "*"
eigen = "*"
geos = "*"
cmake = "*"
ninja = "*"
gmp = "*"
mpfr = "*"

[target.win-64.dependencies]
vs2022_win-64 = "*"

[tasks]
configure = { cmd = "cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$CONDA_PREFIX" }
build = { cmd = "cmake --build build --parallel", depends-on = ["configure"] }
configure-lib = { cmd = "cmake -S demo_lib -B demo_lib/build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DVAL3DITY_LIBRARY=ON" }
build-lib = { cmd = "cmake --build demo_lib/build --parallel", depends-on = ["configure-lib"] }

[target.win-64.tasks]
configure = { cmd = "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$CONDA_PREFIX" }
build = { cmd = "cmake --build build --config Release --parallel", depends-on = ["configure"] }
configure-lib = { cmd = "cmake -S demo_lib -B demo_lib/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DVAL3DITY_LIBRARY=ON" }
build-lib = { cmd = "cmake --build demo_lib/build --config Release --parallel", depends-on = ["configure-lib"] }
